---
- name: Start all AWX containers | config changes
  docker_compose:
    project_name: "awx"
    project_src: "{{ awx_compose_dir }}/"
    restarted: yes
  when: config_state_primary.changed or
        config_state_agent.changed or
        launcher_state_primary.changed or
        launcher_state_agent.changed or
        config_ssh_state.changed or
        ssh_id_state.changed

- name: Start all AWX containers | docker-compose changes
  docker_compose:
    project_name: "awx"
    project_src: "{{ awx_compose_dir }}/"
