ansible_host: 10.13.55.206
awx_node_role_type: execution
# Generate unique value with `echo 'import uuid; print(uuid.uuid4())' | /usr/bin/python3`
awx_cluster_node_system_uuid: 9f549e23-d167-48fc-9d94-993b96c4d209

awx_receptor_crt: |
  -----BEGIN CERTIFICATE-----
  MIIEYTCCAkmgAwIBAgIEY1HLbjANBgkqhkiG9w0BAQsFADAkMSIwIAYDVQQDDBlB
  V1ggRGVtbyBSZWNlcHRvciBSb290IENBMB4XDTIyMTAyMDIyMjc1OFoXDTI0MTAy
  MDIyMjc1OFowLDEqMCgGA1UEAxMhYXd4LXJlY2VwdG9yLWJlaGluZC1ob3AtMS5k
  ZW1vLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvjP1YLsFG0zC
  /e/toRS8P4RWggTyRYMJYBW5NbDWlU2I6O/z0iyoA2svKNIZPrBRwctZa6KldLLc
  45gCddpXsNoUzklJMBkXvhZjt9QgFZza89gBr0t0KtprSnMAK25LscVnSK/rjB0S
  j6NVWMQPAwfUzZV+UjX+G+P7eGoz5erENLyMyRM9AQI28Eic+LXUZR31AALKJURF
  nNCLHluBi+FC461DQKYyXYEVgbvpuAz5VPEkk9vCU2w0mzKO8KFqiIy1hYzcvHTg
  7QWlz74u3FSopVJ+Z1DqkWpJeT3uNz9/iJQz7UWhhW5Yy3QGrQlwpm+Rp3QR7qLY
  9l364a/fGQIDAQABo4GSMIGPMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggr
  BgEFBQcDAgYIKwYBBQUHAwEwXgYDVR0RBFcwVYIhYXd4LXJlY2VwdG9yLWJlaGlu
  ZC1ob3AtMS5kZW1vLmlvoDAGCSsGAQQBkggTAaAjDCFhd3gtcmVjZXB0b3ItYmVo
  aW5kLWhvcC0xLmRlbW8uaW8wDQYJKoZIhvcNAQELBQADggIBAEqLs4lk96GZL9mv
  EbmUjzA78+mcORkS+YyoJoPwMPSDnWPFFHuKW7BpMyw+2nIjCg8GY/cTDC/3A+O6
  l9OctoXMBnhyGJsOeaUAW6r+zLVaq2UXFPNrGy1AA4YTjxcl5ACdYzDvtp+clBq6
  JZ/izOmr9JprNVrUGZgqfukXi2EUjrOtHnBhFZFnSPix3Ji69yTVMFPATWZl6Ka8
  WPg9S0aCuxp7RtB3QEiIUsiHFZNm7x12yem63KWD3QczcqaAmpDGc4oaffMjk3A6
  b4LMk6nE3Fh8Zzdqss1ZeXpyvTV1KsRXmK6S58KmAHDLCqPTIpni52bbDTLnhRxi
  81s16Hx44SWt4vy1dtx2hnikXK/B71Wl1rRCY4+Q+nGNCMjBMpvuW/qqazZj86Go
  im2Q5/i1yF2MspsnpVBvMa4VR/QABLcGGqzV6uToO1Nq8RwFkopk+HfZlT/HUXIB
  n1wQAYP2LA6THp8nNaDp3BW/ZTGZSDNvh4xY+ZY6I0PxfbuY3DFBBsovjZ/aPUb+
  sC1P589Ti/39iWA2NNhu6oo0303YDMefcQf4KvgPMqiueS01bEQSNtQydVFuf5rc
  LdOnzs+JyBnGsYT5tnAKtghwPiXaZt+x+rNcSxsUOMxDCv0HvQY9bp0ccHCC/epa
  qGrgxT67NDP62HpbcNQDbHMRhbmT
  -----END CERTIFICATE-----

awx_receptor_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAvjP1YLsFG0zC/e/toRS8P4RWggTyRYMJYBW5NbDWlU2I6O/z
  0iyoA2svKNIZPrBRwctZa6KldLLc45gCddpXsNoUzklJMBkXvhZjt9QgFZza89gB
  r0t0KtprSnMAK25LscVnSK/rjB0Sj6NVWMQPAwfUzZV+UjX+G+P7eGoz5erENLyM
  yRM9AQI28Eic+LXUZR31AALKJURFnNCLHluBi+FC461DQKYyXYEVgbvpuAz5VPEk
  k9vCU2w0mzKO8KFqiIy1hYzcvHTg7QWlz74u3FSopVJ+Z1DqkWpJeT3uNz9/iJQz
  7UWhhW5Yy3QGrQlwpm+Rp3QR7qLY9l364a/fGQIDAQABAoIBAQCU4NK2rmzm24Td
  g8n7BeH7zbhw+TIx2smh3h8kuZCdOR1rRzcQUkgItQMq7pk4CodUK7mImLztxXtE
  4p06ZnexRGJ4vcB914ZQEfJn17BtemOf7noTHfqF+IV2tuFxHVo+ggfAS4MSH0eC
  CxUo7/3YH28gpF1GOGD4r9EMhgStd2Yn59KuUcffrby3qz8J5Wvi+hVbBigE8R/u
  F2KY3OxNTmLICeR4W+5uM/TWH2XT/zX1W2jmc1FFyMi24/Ek+qMvgvbvFN9Qq+X3
  xyXqqbmIL/PuGuGxW4hJCASfZKzLaczaYVcFGBMSyxs2ILLISzJfd1J2kziqMDl0
  2z10CNHJAoGBAOHB/eOyLIN9+jOtHBY5WTJj3G4UAO64cuy5ONWfsH2aPmVDvZp3
  0Z82BhYmLSyCqFQgD8GuwTDPJL7LveQKwMb4SrXBGTlpZMNgn07rOvNdcZA96fyo
  XLVCx5bRVzsVO5+6pQq/Fyc899eHmjGPUvPxKVa16ZgnQYPRGPlvjVv7AoGBANeu
  q5BqfSz7yDkNasDzTNWLVPK9cFcnGwB7b3ZqD1PcGp23B1JMfIJqY/TWXw+DmSex
  p52X4WjCXCsGb+0tLp5sL6RaJWps96EMYRS9fTaD//gvcPi8qYXhUDKQYTROILKe
  uT8++VQcna4QKQlNHLpljvYdo1oVG2NklbrGVRD7AoGASJA7FBnr9uPiLQQCWB5c
  zjaM3pDtb823muE6JGfsqaKPVas9YU4MAbmyoSHqOTlR86BOkDmkfRTHwc/pHEhc
  iFe8Y8lKW0rGCYqgChTP4PNzEiLkd8KB8f0h/BcTi7kabg/nBpo/Texp2UwLwsxH
  pIMqf2V/TNmpVD48Ych6TksCgYEAk+8LX9+agfskZvVr7nIylhmeJ2yGHFEHNTp0
  xjySzMsgOmLqk6lAkVcVvj43L3Xs24v/0pj1E5yUCTK+HGisHB9KQilOloOtCXpr
  MAWUV4sMS5eGniURBXH4RuY+tdiMltdFajrwWp/SCyysaOPKO5MjDm5ft47YnUDF
  bjlQ6XcCgYEAufS5dLrl1OZwxUle65jtb+ysyp/SxV2HjDe9kMiFwsbebVRCnAmj
  Dq4BGeH1wrVY6OUw8GgOCTV66Mc6isTup6szTBx4xeWaN3Fm87CyuspCOPJjz5mL
  uGswZMIVN0MYmVY1kwJlHeexLuVw7vffs7zoTlBVlCAA9Co3Wj8ZYfI=
  -----END RSA PRIVATE KEY-----
