ansible_host: 10.13.55.207
awx_node_role_type: execution
# Generate unique value with `echo 'import uuid; print(uuid.uuid4())' | /usr/bin/python3`
awx_cluster_node_system_uuid: 1ad10f3c-93fd-402a-ba94-66ae02dc90a0

awx_receptor_crt: |
  -----BEGIN CERTIFICATE-----
  MIIEPjCCAiagAwIBAgIEY1KN0DANBgkqhkiG9w0BAQsFADAkMSIwIAYDVQQDDBlB
  V1ggRGVtbyBSZWNlcHRvciBSb290IENBMB4XDTIyMTAyMTEyMTcyMFoXDTI0MTAy
  MTEyMTcyMFowITEfMB0GA1UEAxMWYXd4LXJlY2VwdG9yLTMuZGVtby5pbzCCASIw
  DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANQDsh1yYBNzn0+2S4+8v6GVBwQH
  7E5+ajIX6d1Hqo6PtswKf1ppDQrAC7Vtr6jbpdaHono7g0R6W0gk6pDNI8YDaWYG
  CGfmN8gI/Xlpgo1nM8dtEhhYvN3woauC5IzNo424DeNTNBz+xqJvBqbDV184KweY
  PdBc+aZJYg1/zfXQs/L+8Z8Anzzo63huNDmHp4xNkiObDC4mweijpVrKCZF/S7aH
  9tlQuHhrxY7UpbKrU5LRwaCrQKzskbCyd8XUbS74+LzMbPmFra12yjE2VcItz+c6
  5+pHBaX9sTdnC2In/H/GbNkwM/3G+f2Jm7xzRFK42vgRfRtBkMNBDpzr7WsCAwEA
  AaN7MHkwDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
  BQcDATBIBgNVHREEQTA/ghZhd3gtcmVjZXB0b3ItMy5kZW1vLmlvoCUGCSsGAQQB
  kggTAaAYDBZhd3gtcmVjZXB0b3ItMy5kZW1vLmlvMA0GCSqGSIb3DQEBCwUAA4IC
  AQApWtU9F/zr4ZxFjRlYiUGuVrtq/536H3YKvb58l5+EInt6XgEmsoD4zXrFPiuG
  Ghmjs1X2pJwYLXNWMUsdpDHgP45yUkfNU6dNnqveKenel28S1+FiyiFDZ7GKbzo+
  HhKco1bUZNb/tuSn4VjTWhLv5j0GmXIQDY0RMD9r9UkRYE6MltBwYMdb5kD5QReA
  YfdE4Ov7ISZp3w/2PrqX1o5oeODl68QLD05zzUjml3HOzIAxzhnU6CYlh8++R4zM
  ZGzpyLJThpeMQiqXNaDNGF+i54v60zBpbBCUmkgPmH3h9HVhi6U1jGMqF4e5pAg3
  ufD7pJkqeFPQm4zH6oJhkyBTWtyJNybfnQ5ecsYEFgOeBxdLG8LDO3y8RlOEjUk6
  W7SpAsWfFcL9n6vPT//fdCu54P0KgqKRR5A0SuAuUiB0wctFIfng15rBTy+cGjIM
  cl6phKl+0PW5Vy+FyIF8avBbXbJj2cyywjAsUiB/Z0zOxXwPN1QLhJSIABh/GprW
  YiHZZRk/VFCVgWWuJDqj5N+NubQXzU+eZP3xC9Ax4Y5S9cF5f3q3VMq5RarxDKxH
  07ACxkl6tG0bwpdqOrA1PNkR7Qta7Xcrz8iYmCyiwpCLdDKrL75fM1pXNNnZi1m5
  I45dvW68AjcheSb5121w5pgWXO6aHUTiDOittOySoeT22g==
  -----END CERTIFICATE-----

awx_receptor_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA1AOyHXJgE3OfT7ZLj7y/oZUHBAfsTn5qMhfp3Ueqjo+2zAp/
  WmkNCsALtW2vqNul1oeiejuDRHpbSCTqkM0jxgNpZgYIZ+Y3yAj9eWmCjWczx20S
  GFi83fChq4LkjM2jjbgN41M0HP7Gom8GpsNXXzgrB5g90Fz5pkliDX/N9dCz8v7x
  nwCfPOjreG40OYenjE2SI5sMLibB6KOlWsoJkX9Ltof22VC4eGvFjtSlsqtTktHB
  oKtArOyRsLJ3xdRtLvj4vMxs+YWtrXbKMTZVwi3P5zrn6kcFpf2xN2cLYif8f8Zs
  2TAz/cb5/YmbvHNEUrja+BF9G0GQw0EOnOvtawIDAQABAoIBAC2ytjueoZLPwzD9
  TAApYOzFIIP/6TFqEh3GBcSKY/rigzYrtROZvRPqHRv4DnrJDU/WYHEUTtD9xpsg
  Seb4MJPHvHofJsSuXKujNG9tDJTJ/+EmY1YYGm2EJnS/e9/Vm0E6wNOU5ZCyYcI1
  SCu9wyFlC/FRIVG+GJl9C8N5Hr2y37wb4m81wx5kdULUuZ9T/jUaXdKg0NMB3wu9
  mzNS03VVnJBN3QFzHW4n4NBIaHRLfOx05keEnRgnVa5ooXnU0EtHbPf8IkAsSQSv
  CsPgf9oCr5DtMB/73OiTQR5qZqVcBMJVgeK6d5m6GwlL8g6pWI2wbJwnCvNA+mnz
  sBzuPEECgYEA+5VF7bURi+6k1arQCvdrjODG1Fmxrtm5TKBz0Pq8+spwul1BPLiA
  aWkAZg8VR2WBopHxJAmg0kpfXhptqdo+iZN52+f7/CjpBqExEIZ79J6yGZ/sKgIz
  BKiQDUsumlB46KyWsus4F1E91RvPRJMbWSDS+VVetnOqd9y3ykmyJzECgYEA17yV
  VxOmCQunqDXlRB1vxD3WgBTRokV7YBXnJA/EccKm3z3CJ5CgxoBfP+PoPVd+aSFR
  8OkC4Y7xtmaQfIqWigs1mlKshHRJHzgzUprm90sW6/b5eVh5i/uBHAueFxzfIu7M
  6vcPcq4sDXEh55+7LCCp7SasacC1nywWxF5GL1sCgYBfNrBfdU6tueSyZNIVxGv0
  xkEZrtR7SzVA1dzfM3YAKEufjJmbBGy8+BtJhN3VxonYYAl2TRqLW9BaCgCE7u8K
  HEFbQ6HvXgBLHQg3q94Px1u6LPcxMuHiGnViQpjhmCEaVe82yaTR1lJjbAH2fwIz
  qiOOb4vH22ChumvoaBm/kQKBgQCIZneVopqrxW6vb8QRGPt9fAuO15rjmkKzMaX+
  qultc8DGDOog0dSVLL0MTDCd+B+4oJSKWQi1TAePZ7GazJT5mrS9aeAhrtQ8pO/u
  HnpBiHxpnLGHA2V2GAI9lSrTOjHqiEmPlb1yqKS5qvng1KEm+U/23SjNhEZQ6TNL
  3L9LWQKBgQDV/DA+jrGyZURY2sKCRFxwOVuaXKCw70Ro7uG9tsIOUnUQ7GJR3k4X
  SJTLsAItD4IlR5fUy4pRKOWLLX2vG++ZDHEOMh9+qQg2zEXAnrX8stVFm862168O
  QN8Ehn/3k47M9TUshyWu1chRAquPPT4cDSriCF4I1Un6swkF6oHAkQ==
  -----END RSA PRIVATE KEY-----
